#!/bin/bash
# Project-specific gate commands
# Sourced by .dev_cycle/gates.sh
#
# Generated by /init-dev-cycle. Edit to match your project's build/test commands.
#
# Required functions:
#   run_iteration_gate — quick checks after each implementation phase (gates.sh iteration)
#   run_pre_pr_gate    — full checks before creating a PR
#   run_final_gate     — clean build verification after merge
#   should_run_codegen — return 0 (yes) or 1 (no)
#   run_codegen        — generate code (if applicable)

# ---------------------------------------------------------------------------
# Codegen (optional — e.g. dart build_runner, prisma generate, openapi-codegen)
# ---------------------------------------------------------------------------

# Return 0 to run codegen, 1 to skip.
# Example: check if any model files changed before running
should_run_codegen() {
  return 1  # default: no codegen
}

run_codegen() {
  # Example for Flutter/Dart:
  #   dart run build_runner build --delete-conflicting-outputs
  # Example for Prisma:
  #   npx prisma generate
  echo "No codegen configured. Update gates_config.sh."
}

# ---------------------------------------------------------------------------
# Iteration gate — run after each implementation phase (same rhythm as project.yaml implementation_phases)
# ---------------------------------------------------------------------------

run_iteration_gate() {
  # Example for Flutter:
  #   flutter analyze --no-fatal-infos || return 1
  #   flutter test || return 1

  # Example for React Native + FastAPI:
  #   (cd frontend && npx tsc --noEmit) || return 1
  #   (cd backend && python -m pytest -q) || return 1

  # TODO: replace with your project's commands
  echo "No iteration gate configured. Update .dev_cycle/gates_config.sh."
  return 0
}

# ---------------------------------------------------------------------------
# Pre-PR gate — full validation before opening a pull request
# ---------------------------------------------------------------------------

run_pre_pr_gate() {
  # Often the same as iteration gate, possibly with stricter flags.
  # Example for Flutter:
  #   flutter analyze --no-fatal-infos || return 1
  #   flutter test || return 1

  run_iteration_gate
}

# ---------------------------------------------------------------------------
# Final gate — post-merge clean build verification
# ---------------------------------------------------------------------------

run_final_gate() {
  # Example for Flutter:
  #   flutter clean
  #   flutter pub get
  #   run_codegen
  #   flutter analyze --no-fatal-infos || return 1
  #   flutter test || return 1

  run_iteration_gate
}
